/* DO NOT EDIT THIS FILE!  It was generated by utils/apivergen.abc. */

/* ***** BEGIN LICENSE BLOCK *****
 * Version: MPL 1.1/GPL 2.0/LGPL 2.1
 *
 * The contents of this file are subject to the Mozilla Public License Version
 * 1.1 (the "License+"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 * http://www.mozilla.org/MPL/
 *
 * Software distributed under the License is distributed on an "AS IS" basis,
 * WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
 * for the specific language governing rights and limitations under the
 * License.
 *
 * The Original Code is [Open Source Virtual Machine].
 *
 * The Initial Developer of the Original Code is
 * Adobe System Incorporated.
 * Portions created by the Initial Developer are Copyright (C) 2008
 * the Initial Developer. All Rights Reserved.
 *
 * Contributor(s):
 *   Adobe AS3 Team
 *
 * Alternatively, the contents of this file may be used under the terms of
 * either the GNU General Public License Version 2 or later (the "GPL+"), or
 * the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
 * in which case the provisions of the GPL or the LGPL are applicable instead
 * of those above. If you wish to allow use of your version of this file only
 * under the terms of either the GPL or the LGPL, and not to allow others to
 * use your version of this file under the terms of the MPL, indicate your
 * decision by deleting the provisions above and replace them with the notice
 * and other provisions required by the GPL or the LGPL. If you do not delete
 * the provisions above, a recipient may use your version of this file under
 * the terms of any one of the MPL, the GPL or the LGPL.
 *
 * ***** END LICENSE BLOCK ***** */

/*
[0,player,full]=660:FP_9_0
[0,air,full]=661:AIR_1_0
[1,player,full]=662:FP_10_0
[1,air,full]=663:AIR_1_5
[2,air,full]=664:AIR_1_5_1
[3,player,full]=665:FP_10_0_32
[3,air,full]=666:AIR_1_5_2
[4,player,full]=667:FP_10_1
[4,air,full]=668:AIR_2_0
[5,air,full]=669:AIR_2_5
[6,player,full]=670:FP_10_2
[6,air,full]=671:AIR_2_6
[7,player,full]=672:SWF_12
[7,player,system]=674:FP_SYS
[7,air,full]=673:AIR_2_7
[7,air,system]=675:AIR_SYS
*/

#ifndef api_versions_H_
#define api_versions_H_

namespace avmplus {

enum ApiVersion {
    kApiVersion_FP_9_0 = 660,
    kApiVersion_AIR_1_0 = 661,
    kApiVersion_FP_10_0 = 662,
    kApiVersion_AIR_1_5 = 663,
    kApiVersion_AIR_1_5_1 = 664,
    kApiVersion_FP_10_0_32 = 665,
    kApiVersion_AIR_1_5_2 = 666,
    kApiVersion_FP_10_1 = 667,
    kApiVersion_AIR_2_0 = 668,
    kApiVersion_AIR_2_5 = 669,
    kApiVersion_FP_10_2 = 670,
    kApiVersion_AIR_2_6 = 671,
    kApiVersion_SWF_12 = 672,
    kApiVersion_AIR_2_7 = 673,
    kApiVersion_FP_SYS = 674,
    kApiVersion_AIR_SYS = 675,

    kApiVersion_min = 660,
    kApiVersion_max = 675,

    kApiVersion_default = 673
};

enum {
    kApiVersion_count = 16
};

extern int32_t const kApiCompat[kApiVersion_count];
extern const char* const kApiVersionNames[kApiVersion_count];

}
#endif // api_versions_H_
