#!/bin/bash

# usage: avmwrap <avm-path> options...
#
# This script wraps execution of the given avm, and appends the commandline
# to test.sh in the current directory.  Use with test/acceptance/runtest.py
# or test/performance/runtest.py as follows:
#
# runtest.py --avm="avmpath <real-avm-path>" ...

avm=$1; shift
echo $avm "$@" >>test.sh
$avm "$@"
